### ISSUE TITLE
ansible-galaxy role 404s 

### ISSUE THREAD

**Issue by scrungus** [mrlesmithjr/ansible-manage-lvm#105]
**Describe the bug**
Looks like something has gone wrong with the latest release as the role is no longer available on ansible-galaxy 

**To Reproduce**
1. Go to `https://galaxy.ansible.com/mrlesmithjr/manage-lvm` 
2. Get a 404 😁

**Comment by jackhodgkiss** [comment]
Looks like it has been renamed to https://galaxy.ansible.com/mrlesmithjr/manage_lvm.

This appear to be the issue: https://github.com/mrlesmithjr/ansible-manage-lvm/blob/11056e2e604b98771785763956a7da0a7d302fcc/meta/main.yml#L6

**Comment by jantari** [comment]
Yep, ran into the same error here as well.

This is the commit with the rename: d27a3809d90bdbb77ab77ff7b45b1337c728f2ec

Updating your **requirements.yml** file from:

```yaml
- name: lvm
  src: mrlesmithjr.manage-lvm
```

to

```yaml
- name: lvm
  src: mrlesmithjr.manage_lvm
```

fixes it
