### ISSUE TITLE
README description clarifying extending lvm

### ISSUE THREAD

**Issue by daurrutia** [mrlesmithjr/ansible-manage-lvm#15]
Thank you for your work on this. It is wonderful.

I would like to ask the question: What is the process to extend a volume?
Add an additional disk to the list of disks? and Increase the size?

I noticed the conditional to run the resize tasks references lvm['changed']. Is that the lvm_groups?

Just looking for a little clarification. Thanks!

**Comment by mrlesmithjr** [comment]
@daurrutia Sorry for the late response on this. You have it dead on as the way it should work. Hopefully you have been able to clarify this already. And very much appreciated and hopefully this role has been useful for you.

**Comment by daurrutia** [comment]
Yes got it figured out. Thanks.

**Comment by mrlesmithjr** [comment]
Awesome! Glad you got it figured out.
