### ISSUE TITLE
Error with XFS filesystem

### ISSUE THREAD

**Issue by smutel** [mrlesmithjr/ansible-manage-lvm#26]
Error received when creating XFS filesystems:

> failed: [consul-itg-01] (item=[{u'vgname': u'vg02', u'disks': [u'/dev/vdb1'], u'create': True}, {u'lvname': u'consul-data', u'filesystem': u'xfs', u'mntp': u'/opt/consul/data', u'create': True, u'mount': True, u'size': u'5g'}]) => {"ansible_loop_var": "item", "changed": true, "cmd": ["xfs_growfs", "-d", "/dev/vg02/consul-data"], "delta": "0:00:00.005995", "end": "2019-10-14 11:57:37.229978", "item": [{"create": true, "disks": ["/dev/vdb1"], "vgname": "vg02"}, {"create": true, "filesystem": "xfs", "lvname": "consul-data", "mntp": "/opt/consul/data", "mount": true, "size": "5g"}], "msg": "non-zero return code", "rc": 1, "start": "2019-10-14 11:57:37.223983", "stderr": "xfs_growfs: /dev/vg02/consul-data is not a mounted XFS filesystem", "stderr_lines": ["xfs_growfs: /dev/vg02/consul-data is not a mounted XFS filesystem"], "stdout": "", "stdout_lines": []}

xfs_growfs is using a mounted partition as parameter and not a LVM mapper.

**Comment by mrlesmithjr** [comment]
@smutel Thanks for reporting this. There are a few things we will need to figure out from this. First off, the main purpose of this role is to manage LVM based elements. Now, I am not opposed to adding this additional functionality if it makes sense to everyone. I do know that this role is used pretty extensively in many different environments and this change could possibly break some things which we do not want to do. So I will ask that we get others to chime in on their thoughts and etc. Thank you also for taking the time to submit the PR, but let's just get everyone to review it and do the right thing. 🥇 


/cc @markgoddard @zoobert @faisalnizam

**Comment by smutel** [comment]
No problem.  
For info it's not an additional functionality, it's bug fixed of an existing functionality.

**Comment by markgoddard** [comment]
Thanks for tagging me @mrlesmithjr. My understanding of the issue aligns with @smutel - the role already tries to grow an XFS filesystem, but passes the devicemapper device to xfs_growfs, rather than the mount point.

**Comment by mrlesmithjr** [comment]
Thanks @markgoddard. And again thanks @smutel for reporting this.
