### ISSUE TITLE
Xfs not working on centos machines

### ISSUE THREAD

**Issue by Tcharl** [mrlesmithjr/ansible-manage-lvm#31]
Hi,

xfstools are not installed on centos like machines, thus failing xfs mountpoint

I did a huge PR adding molecule tests and fixing that case.

**Comment by Tcharl** [comment]
Yes, I thought to make a fork at first: I had some additional features on top of it, but then decided to give back the original code.

This roles has been very useful to me so you totally owe it :-).
I hope you'll enjoy 5 star lint results on Ansible galaxy as well as some additional CI and automated tests. I'll also contribute back the fully automated ci (with integration tests) while I succeed to make it work with github actions or travis.

**Comment by Tcharl** [comment]
Hi,

I tried all my best for CI and molecule, but unfortunately, it won't be possible.
The good news is that it will only be impossible for LVM related roles and possible for the others.

For container-friendly roles, it can be achieved using github actions, see [this one](https://github.com/OsgiliathEnterprise/ansible-users) for example

For the others, you can use travis molecule-vagrant and vagrant-libvirt can be used: https://github.com/OsgiliathEnterprise/ansible-volumes The bad news being that travis (or vagrant-libvirt) being incompatible with vagrant-persistent-storage, thus not mounting the harddisk to execute lvm tests onto...

**Comment by mrlesmithjr** [comment]
No worries on this. All of my roles are over time getting refactored using https://github.com/mrlesmithjr/cookiecutter-ansible-role which includes all CI/molecule testing. Latest versions of Molecule don't support Vagrant anyways, or at least the last time I checked. Again, thanks for your contribution.

**Comment by mrlesmithjr** [comment]
I see you referenced this https://github.com/ansible-community/molecule-vagrant. Haven't seen this yet.
