### ISSUE TITLE
Cannot run module with Ansible 2.2

### ISSUE THREAD

**Issue by zoobert** [mrlesmithjr/ansible-manage-lvm#4]
Changes to Ansible deprecated the use of bare vars in playbooks. This meant some of the tasks that used with_* could not be executed. Per Ansible's [release notes](https://docs.ansible.com/ansible/porting_guide_2.0.html#deprecated), the deprecated functionality to use bare vars was removed in Ansible 2.2.

This module cannot be run in its current state using code in `manage_lvm.yml` that uses the bare vars syntax. These need to be modified to use the new syntax:

```
  with_subelements:
    - "{{ lvm_groups }"
    - lvnames
```

**Comment by mrlesmithjr** [comment]
@zoobert - Thanks for the contribution.
