### ISSUE TITLE
extending volume

### ISSUE THREAD

**Issue by emper0r** [mrlesmithjr/ansible-manage-lvm#47]
Hi @mrlesmithjr, 
we noted you removed xfs resize capability, commented as

# unable to resize xfs: looks like we've to reference the mountpoint instead of the device
in https://github.com/mrlesmithjr/ansible-manage-lvm/blob/master/tasks/create_fs.yml
related I suppose to commits:

> 17e8ec1058c5cb66b21b15a8d3912ac9980508a9
> 4a1177e420fd9632f77d07ce0a19f89a1515f8eb

We noted on CentOS 7 normally LV Path works (e.g. xfs_growfs {LV Path}), on other version (probably CentOS8) works with mount point (xfs_growfs /mountpiunt).

On CentOS 7 this role does not extend xfs filesystem any more.

**Comment by mrlesmithjr** [comment]
@emper0r Thanks for reporting this. @Tcharl Is this something you can look into and ensure that XFS for CentOS 7 and CentOS 8 both work? Likely just a conditional to account for both versions on two separate tasks would work fine.

**Comment by Tcharl** [comment]
Sure, I'll see what I can do, but I can't tell when (in the month I guess): @emper0r can't you PR?

I guess it will be another task step, and that it never worked before (the previous code i create_lv.yml also referenced the device).

**Comment by mrlesmithjr** [comment]
@Tcharl Sounds good. We also need to review #45 to ensure things are still good to go. I'd also recommend that @emper0r leverage one of the releases that works for now if that is cool.

**Comment by emper0r** [comment]
Hi. sorry for delay, and thanks for the answer.. for now when I need it to extend another one I'll rollback into the commit to identify what I need to tagged and notice here. In the meanwhile thanks very much for all your work :)
